version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: .docker/development/Dockerfile
    entrypoint: .docker/run_tests.sh
    env_file:
      - .env.test
    volumes:
      - .:/app
